# Generated by Django 5.2.2 on 2026-08-04 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('url', models.URLField(unique=True)),
                ('parse_date', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, choices=[('youtube', 'Ютуб'), ('vk', 'Вк')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchIPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_mappings', to='common_parser.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BranchPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('yandex', 'Yandex'), ('2gis', '2GIS'), ('vlru', 'VL.ru')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('org_id', models.CharField(blank=True, max_length=128, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('review_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='common_parser.branch')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='common_parser.organization'),
        ),
        migrations.CreateModel(
            name='PlaylistIPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_mappings_playlist', to='common_parser.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('photos', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.CharField(blank=True, null=True)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('review_url', models.URLField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('branch_platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='common_parser.branchplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('preview', models.URLField(blank=True, max_length=1000, null=True)),
                ('duration', models.IntegerField(blank=True, default=None, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='common_parser.playlist')),
            ],
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'address'), name='unique_organization_address'),
        ),
    ]
