# Generated by Django 5.2.2 on 2026-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='playlist',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branchplatform',
            name='provider',
            field=models.CharField(choices=[('yandex', 'Yandex'), ('2gis', '2GIS'), ('vlru', 'VL.ru')], max_length=20),
        ),
    ]
