# Generated by Django 5.2.2 on 2026-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0026_branch_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
