# Generated by Django 5.2.2 on 2026-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_parser', '0027_review_external_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branchplatform',
            name='unique_branch_provider',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
